#on: [workflow_dispatch]
on:
 push:
   paths:
     - 'api/CustomerAPI/**'
     - '.github/workflows/*'

name: Customer Api
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      directory: api/CustomerAPI
      name: vlabrd
      
    steps:
    - uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build image with Azure Container Registry
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az acr build --registry acr${{ env.name }}.azurecr.io --image customerapi:${{ github.run_number }} . -f api/CustomerAPI/Dockerfile

    - name: Use dotnet tools to build and generate swagger
      run: |
        dotnet tool restore --tool-manifest .config/dotnet-tools.json
        dotnet restore 
        dotnet build
        dotnet swagger tofile --output $GITHUB_WORKSPACE/api/CustomerAPI/swagger-output/swagger.json $GITHUB_WORKSPACE/api/CustomerAPI/bin/Debug/net6.0/CustomerAPI.dll v1
      working-directory: ${{ env.directory }}